//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalsificacionEntrada.Clasificacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://motor", ConfigurationName="Clasificacion.WSClasificacion")]
    public interface WSClasificacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCarroClasificacionReturn")]
        object[] getCarroClasificacion(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCarroClasificacionReturn")]
        System.Threading.Tasks.Task<object[]> getCarroClasificacionAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="generarPreclasificacionEntradasReturn")]
        string generarPreclasificacionEntradas(string json, string[] identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="generarPreclasificacionEntradasReturn")]
        System.Threading.Tasks.Task<string> generarPreclasificacionEntradasAsync(string json, string[] identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="hayClasificacionEntradasReturn")]
        bool hayClasificacionEntradas(int idRecepcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="hayClasificacionEntradasReturn")]
        System.Threading.Tasks.Task<bool> hayClasificacionEntradasAsync(int idRecepcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getExistenciaClasificacionReturn")]
        object[] getExistenciaClasificacion(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getExistenciaClasificacionReturn")]
        System.Threading.Tasks.Task<object[]> getExistenciaClasificacionAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="generarEntradaEnCarroPTLReturn")]
        int generarEntradaEnCarroPTL(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, int cantidad, int cantidadUnidad, object[] atributos, int idHueco, int idOperario, int idRecurso, int estado, string lote, string[] identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="generarEntradaEnCarroPTLReturn")]
        System.Threading.Tasks.Task<int> generarEntradaEnCarroPTLAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, int cantidad, int cantidadUnidad, object[] atributos, int idHueco, int idOperario, int idRecurso, int estado, string lote, string[] identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void asignarHuecoACarro(int idHueco, int idCarro, string subSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task asignarHuecoACarroAsync(int idHueco, int idCarro, string subSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void asignarPaletMultiASubsistema(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idEntrada, string subsistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task asignarPaletMultiASubsistemaAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idEntrada, string subsistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void cerrarMultiReferencia(int idEntradaPadre, string subsistemaClas);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task cerrarMultiReferenciaAsync(int idEntradaPadre, string subsistemaClas);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        void ponerClasificacionTratado(int idEntrada, int idRecepcion, int idPedidoPro, int idPedidoProLin, string subsistema, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task ponerClasificacionTratadoAsync(int idEntrada, int idRecepcion, int idPedidoPro, int idPedidoProLin, string subsistema, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getEntradasMultiPadrePendienteReturn")]
        object[] getEntradasMultiPadrePendiente(int idRecepcion, int idPedidoPro, int idPedidoProLin, string subSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getEntradasMultiPadrePendienteReturn")]
        System.Threading.Tasks.Task<object[]> getEntradasMultiPadrePendienteAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, string subSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCompartimentoCarroClasificacionReturn")]
        object[] getCompartimentoCarroClasificacion(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCompartimentoCarroClasificacionReturn")]
        System.Threading.Tasks.Task<object[]> getCompartimentoCarroClasificacionAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClasificacionesPtesLineaRecepcionReturn")]
        object[] getClasificacionesPtesLineaRecepcion(int idRecepcion, int idPedidoPro, int idPedidoProLin);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getClasificacionesPtesLineaRecepcionReturn")]
        System.Threading.Tasks.Task<object[]> getClasificacionesPtesLineaRecepcionAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getArticulosClasificacionPendientesReturn")]
        object[] getArticulosClasificacionPendientes(int idRecepcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getArticulosClasificacionPendientesReturn")]
        System.Threading.Tasks.Task<object[]> getArticulosClasificacionPendientesAsync(int idRecepcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCompartimentoCarroPorDescripcionReturn")]
        object[] getCompartimentoCarroPorDescripcion(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCompartimentoCarroPorDescripcionReturn")]
        System.Threading.Tasks.Task<object[]> getCompartimentoCarroPorDescripcionAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarPreclasificacionEntradasReturn")]
        string confirmarPreclasificacionEntradas(string json, string[] identificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="confirmarPreclasificacionEntradasReturn")]
        System.Threading.Tasks.Task<string> confirmarPreclasificacionEntradasAsync(string json, string[] identificador);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSClasificacionChannel : CalsificacionEntrada.Clasificacion.WSClasificacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSClasificacionClient : System.ServiceModel.ClientBase<CalsificacionEntrada.Clasificacion.WSClasificacion>, CalsificacionEntrada.Clasificacion.WSClasificacion {
        
        public WSClasificacionClient() {
        }
        
        public WSClasificacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSClasificacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClasificacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClasificacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object[] getCarroClasificacion(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema) {
            return base.Channel.getCarroClasificacion(idRecepcion, idPedidoPro, idPedidoProLin, idArticulo, subsistema);
        }
        
        public System.Threading.Tasks.Task<object[]> getCarroClasificacionAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema) {
            return base.Channel.getCarroClasificacionAsync(idRecepcion, idPedidoPro, idPedidoProLin, idArticulo, subsistema);
        }
        
        public string generarPreclasificacionEntradas(string json, string[] identificador) {
            return base.Channel.generarPreclasificacionEntradas(json, identificador);
        }
        
        public System.Threading.Tasks.Task<string> generarPreclasificacionEntradasAsync(string json, string[] identificador) {
            return base.Channel.generarPreclasificacionEntradasAsync(json, identificador);
        }
        
        public bool hayClasificacionEntradas(int idRecepcion) {
            return base.Channel.hayClasificacionEntradas(idRecepcion);
        }
        
        public System.Threading.Tasks.Task<bool> hayClasificacionEntradasAsync(int idRecepcion) {
            return base.Channel.hayClasificacionEntradasAsync(idRecepcion);
        }
        
        public object[] getExistenciaClasificacion(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema) {
            return base.Channel.getExistenciaClasificacion(idRecepcion, idPedidoPro, idPedidoProLin, idArticulo, subsistema);
        }
        
        public System.Threading.Tasks.Task<object[]> getExistenciaClasificacionAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema) {
            return base.Channel.getExistenciaClasificacionAsync(idRecepcion, idPedidoPro, idPedidoProLin, idArticulo, subsistema);
        }
        
        public int generarEntradaEnCarroPTL(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, int cantidad, int cantidadUnidad, object[] atributos, int idHueco, int idOperario, int idRecurso, int estado, string lote, string[] identificador) {
            return base.Channel.generarEntradaEnCarroPTL(idRecepcion, idPedidoPro, idPedidoProLin, idArticulo, cantidad, cantidadUnidad, atributos, idHueco, idOperario, idRecurso, estado, lote, identificador);
        }
        
        public System.Threading.Tasks.Task<int> generarEntradaEnCarroPTLAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, int cantidad, int cantidadUnidad, object[] atributos, int idHueco, int idOperario, int idRecurso, int estado, string lote, string[] identificador) {
            return base.Channel.generarEntradaEnCarroPTLAsync(idRecepcion, idPedidoPro, idPedidoProLin, idArticulo, cantidad, cantidadUnidad, atributos, idHueco, idOperario, idRecurso, estado, lote, identificador);
        }
        
        public void asignarHuecoACarro(int idHueco, int idCarro, string subSistema) {
            base.Channel.asignarHuecoACarro(idHueco, idCarro, subSistema);
        }
        
        public System.Threading.Tasks.Task asignarHuecoACarroAsync(int idHueco, int idCarro, string subSistema) {
            return base.Channel.asignarHuecoACarroAsync(idHueco, idCarro, subSistema);
        }
        
        public void asignarPaletMultiASubsistema(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idEntrada, string subsistema) {
            base.Channel.asignarPaletMultiASubsistema(idRecepcion, idPedidoPro, idPedidoProLin, idEntrada, subsistema);
        }
        
        public System.Threading.Tasks.Task asignarPaletMultiASubsistemaAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idEntrada, string subsistema) {
            return base.Channel.asignarPaletMultiASubsistemaAsync(idRecepcion, idPedidoPro, idPedidoProLin, idEntrada, subsistema);
        }
        
        public void cerrarMultiReferencia(int idEntradaPadre, string subsistemaClas) {
            base.Channel.cerrarMultiReferencia(idEntradaPadre, subsistemaClas);
        }
        
        public System.Threading.Tasks.Task cerrarMultiReferenciaAsync(int idEntradaPadre, string subsistemaClas) {
            return base.Channel.cerrarMultiReferenciaAsync(idEntradaPadre, subsistemaClas);
        }
        
        public void ponerClasificacionTratado(int idEntrada, int idRecepcion, int idPedidoPro, int idPedidoProLin, string subsistema, int id) {
            base.Channel.ponerClasificacionTratado(idEntrada, idRecepcion, idPedidoPro, idPedidoProLin, subsistema, id);
        }
        
        public System.Threading.Tasks.Task ponerClasificacionTratadoAsync(int idEntrada, int idRecepcion, int idPedidoPro, int idPedidoProLin, string subsistema, int id) {
            return base.Channel.ponerClasificacionTratadoAsync(idEntrada, idRecepcion, idPedidoPro, idPedidoProLin, subsistema, id);
        }
        
        public object[] getEntradasMultiPadrePendiente(int idRecepcion, int idPedidoPro, int idPedidoProLin, string subSistema) {
            return base.Channel.getEntradasMultiPadrePendiente(idRecepcion, idPedidoPro, idPedidoProLin, subSistema);
        }
        
        public System.Threading.Tasks.Task<object[]> getEntradasMultiPadrePendienteAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, string subSistema) {
            return base.Channel.getEntradasMultiPadrePendienteAsync(idRecepcion, idPedidoPro, idPedidoProLin, subSistema);
        }
        
        public object[] getCompartimentoCarroClasificacion(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema) {
            return base.Channel.getCompartimentoCarroClasificacion(idRecepcion, idPedidoPro, idPedidoProLin, idArticulo, subsistema);
        }
        
        public System.Threading.Tasks.Task<object[]> getCompartimentoCarroClasificacionAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin, int idArticulo, string subsistema) {
            return base.Channel.getCompartimentoCarroClasificacionAsync(idRecepcion, idPedidoPro, idPedidoProLin, idArticulo, subsistema);
        }
        
        public object[] getClasificacionesPtesLineaRecepcion(int idRecepcion, int idPedidoPro, int idPedidoProLin) {
            return base.Channel.getClasificacionesPtesLineaRecepcion(idRecepcion, idPedidoPro, idPedidoProLin);
        }
        
        public System.Threading.Tasks.Task<object[]> getClasificacionesPtesLineaRecepcionAsync(int idRecepcion, int idPedidoPro, int idPedidoProLin) {
            return base.Channel.getClasificacionesPtesLineaRecepcionAsync(idRecepcion, idPedidoPro, idPedidoProLin);
        }
        
        public object[] getArticulosClasificacionPendientes(int idRecepcion) {
            return base.Channel.getArticulosClasificacionPendientes(idRecepcion);
        }
        
        public System.Threading.Tasks.Task<object[]> getArticulosClasificacionPendientesAsync(int idRecepcion) {
            return base.Channel.getArticulosClasificacionPendientesAsync(idRecepcion);
        }
        
        public object[] getCompartimentoCarroPorDescripcion(string descripcion) {
            return base.Channel.getCompartimentoCarroPorDescripcion(descripcion);
        }
        
        public System.Threading.Tasks.Task<object[]> getCompartimentoCarroPorDescripcionAsync(string descripcion) {
            return base.Channel.getCompartimentoCarroPorDescripcionAsync(descripcion);
        }
        
        public string confirmarPreclasificacionEntradas(string json, string[] identificador) {
            return base.Channel.confirmarPreclasificacionEntradas(json, identificador);
        }
        
        public System.Threading.Tasks.Task<string> confirmarPreclasificacionEntradasAsync(string json, string[] identificador) {
            return base.Channel.confirmarPreclasificacionEntradasAsync(json, identificador);
        }
    }
}
