using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RumboSGAManager.Model.Entities
{
    public class OArticulo
    {
        public int idarticulo;
        public String referencia;
        public String descripcion;
        public String familia;
        public int cantidad;
        public char idpalettipo;
        public char idunidadtipo;
        public int cantidadunidad;
        public int diascaducidad;
        public int minpicking;
        public int idhuecopicking;
        public int idzonapicking;
        public int idzonaubicacion;
        public int idzonaubicacion2;
        public char idarticulopose;
        public char idarticuloestado;
        public char tipoarticulo;
        public float peso;
        public int idproveedor;
        public char formaubicacion;
        public char estadoentrada;
        public int stockminreab;
        public int stkminalmcen;
        public int stkmaxalmcen;
        public int cantalmaux;
        public int zonalogalmaux;
        public float volumen;
        public int cantaalmaux;
        public String atributo;
        public int capacidadpicking;
        public int topepickable;
        public String camposcomptraza;
        public int idzonagv;
        public int cantalmgv;
        public int factorconversion;
        public char loteestricto;
        public String equivalencia;
        public int idcomentario;
        public float cmd;
        public float rotacion;
        public float costearticulo;
        public float margenmedio;
        public int coberturadeseada;
        public int leadtime;
        public String directorioimagen;
        public String imagen;
        public String consolidable;
        public String consolidar;
        public char conflote;
        public char sinpedido;
        public char clasificacion1;
        public char clasificacion2;
        public char tipodesbordamiento;
        public int idhuecodesb;
        public int pickinguds;
        public int idhuecopickinguds;
        public int stockminreabuds;
        public int idzonapickinguds;
        public int minpickinguds;
        public int capacidadpickinguds;
        public int configurado;
        public float porcentajeexceso;
        public String descripcionvoz;
        public char pedircantcj;
        public char supcantpicking;
        public char idembalaje;
        public char registrotipopalet;
        public int idpropietario;
        public int idalgoritmoubicacion;
        public int idalgoritmoextraccion;
        public int marcacliente;
        public char atributo2;
        public String refproveedor;
        public int sincontrolstock;
        public char capturanserie;
        public int apilabilidad;
        public int idpresentacion;
        public int tiempoproduccionpieza;
        public int tiempopreparacionorden;
        public int tiempomedpi;
        public int tiempomedsc;
        public int tiempomedco;
        public int idzonatrabajopicker;
        public int udspicker;
        public char preparacionzonacaliente;
        public int completocambiante;
        public int tantoxcientocompleto;
        public char registroestadoexistencia;
        public char tipoimputacionunidades;
        public int idformato;
        public char clasificacionplan;
        public int tipopresentacion;
    }
}
