//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumboSGA.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class customFiltersStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal customFiltersStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RumboSGA.Properties.customFiltersStrings", typeof(customFiltersStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acaba con.
        /// </summary>
        internal static string AcabaCon {
            get {
                return ResourceManager.GetString("AcabaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupar.
        /// </summary>
        internal static string Agrupar {
            get {
                return ResourceManager.GetString("Agrupar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        internal static string Añadir {
            get {
                return ResourceManager.GetString("Añadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        internal static string Aplicar {
            get {
                return ResourceManager.GetString("Aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contiene.
        /// </summary>
        internal static string Contiene {
            get {
                return ResourceManager.GetString("Contiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cualquiera.
        /// </summary>
        internal static string Cualquiera {
            get {
                return ResourceManager.GetString("Cualquiera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RadDataFilter Error.
        /// </summary>
        internal static string DataFilterError {
            get {
                return ResourceManager.GetString("DataFilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empieza con.
        /// </summary>
        internal static string EmpiezaCon {
            get {
                return ResourceManager.GetString("EmpiezaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está en lista.
        /// </summary>
        internal static string EnLista {
            get {
                return ResourceManager.GetString("EnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entre.
        /// </summary>
        internal static string Entre {
            get {
                return ResourceManager.GetString("Entre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de lo siguiente es cierto.
        /// </summary>
        internal static string EsCierto {
            get {
                return ResourceManager.GetString("EsCierto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es nulo.
        /// </summary>
        internal static string EsNulo {
            get {
                return ResourceManager.GetString("EsNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está vacio.
        /// </summary>
        internal static string EstaVacio {
            get {
                return ResourceManager.GetString("EstaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresion.
        /// </summary>
        internal static string Expresion {
            get {
                return ResourceManager.GetString("Expresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro de datos.
        /// </summary>
        internal static string FiltroDatos {
            get {
                return ResourceManager.GetString("FiltroDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupar.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Igual.
        /// </summary>
        internal static string Igual {
            get {
                return ResourceManager.GetString("Igual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce un valor.
        /// </summary>
        internal static string IntroduceValor {
            get {
                return ResourceManager.GetString("IntroduceValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor o igual que.
        /// </summary>
        internal static string MayorIgual {
            get {
                return ResourceManager.GetString("MayorIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor que.
        /// </summary>
        internal static string MayorQue {
            get {
                return ResourceManager.GetString("MayorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor o igual que.
        /// </summary>
        internal static string MenorIgual {
            get {
                return ResourceManager.GetString("MenorIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor que.
        /// </summary>
        internal static string MenorQue {
            get {
                return ResourceManager.GetString("MenorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No contiene.
        /// </summary>
        internal static string NoContiene {
            get {
                return ResourceManager.GetString("NoContiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está en lista.
        /// </summary>
        internal static string NoEnLista {
            get {
                return ResourceManager.GetString("NoEnLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está entre.
        /// </summary>
        internal static string NoEntre {
            get {
                return ResourceManager.GetString("NoEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es igual que.
        /// </summary>
        internal static string NoIgual {
            get {
                return ResourceManager.GetString("NoIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es nulo.
        /// </summary>
        internal static string NoNulo {
            get {
                return ResourceManager.GetString("NoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está vacio.
        /// </summary>
        internal static string NoVacio {
            get {
                return ResourceManager.GetString("NoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        internal static string Personalizado {
            get {
                return ResourceManager.GetString("Personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona Campo.
        /// </summary>
        internal static string SelecCampo {
            get {
                return ResourceManager.GetString("SelecCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin filtro.
        /// </summary>
        internal static string SinFiltro {
            get {
                return ResourceManager.GetString("SinFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todo.
        /// </summary>
        internal static string Todo {
            get {
                return ResourceManager.GetString("Todo", resourceCulture);
            }
        }
    }
}
