//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumboSGA.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NombresFormularios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NombresFormularios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RumboSGA.Properties.NombresFormularios", typeof(NombresFormularios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acopios de Producción.
        /// </summary>
        internal static string AcopiosProduccion {
            get {
                return ResourceManager.GetString("AcopiosProduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agencias.
        /// </summary>
        internal static string Agencias {
            get {
                return ResourceManager.GetString("Agencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articulos.
        /// </summary>
        internal static string Articulos {
            get {
                return ResourceManager.GetString("Articulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOM.
        /// </summary>
        internal static string BOM {
            get {
                return ResourceManager.GetString("BOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes-Pedidos.
        /// </summary>
        internal static string ClientesPedidos {
            get {
                return ResourceManager.GetString("ClientesPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combi Palets.
        /// </summary>
        internal static string CombiPalets {
            get {
                return ResourceManager.GetString("CombiPalets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de Tareas.
        /// </summary>
        internal static string ControlTareas {
            get {
                return ResourceManager.GetString("ControlTareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devoluciones de Cliente.
        /// </summary>
        internal static string DevolClientes {
            get {
                return ResourceManager.GetString("DevolClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devoluciones Proveedor.
        /// </summary>
        internal static string DevolProveedor {
            get {
                return ResourceManager.GetString("DevolProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devoluciones Proveedor Pendientes.
        /// </summary>
        internal static string DevolucionesProPendientes {
            get {
                return ResourceManager.GetString("DevolucionesProPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devolucion Proveedor.
        /// </summary>
        internal static string DevolucionPro {
            get {
                return ResourceManager.GetString("DevolucionPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Existencias.
        /// </summary>
        internal static string EstadoExistencias {
            get {
                return ResourceManager.GetString("EstadoExistencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Fabricación.
        /// </summary>
        internal static string EstadoFab {
            get {
                return ResourceManager.GetString("EstadoFab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Máquina.
        /// </summary>
        internal static string EstadoMaq {
            get {
                return ResourceManager.GetString("EstadoMaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado-Pedidos.
        /// </summary>
        internal static string EstadoPedidos {
            get {
                return ResourceManager.GetString("EstadoPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Tareas.
        /// </summary>
        internal static string EstadoTareas {
            get {
                return ResourceManager.GetString("EstadoTareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existencias Histórico.
        /// </summary>
        internal static string ExistenciasHist {
            get {
                return ResourceManager.GetString("ExistenciasHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expediciones.
        /// </summary>
        internal static string Expediciones {
            get {
                return ResourceManager.GetString("Expediciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias.
        /// </summary>
        internal static string Familias {
            get {
                return ResourceManager.GetString("Familias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formatos SCC.
        /// </summary>
        internal static string FormatosSCC {
            get {
                return ResourceManager.GetString("FormatosSCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencias Inventario.
        /// </summary>
        internal static string IncidenciasInventario {
            get {
                return ResourceManager.GetString("IncidenciasInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inventario Inicial.
        /// </summary>
        internal static string InventarioInicial {
            get {
                return ResourceManager.GetString("InventarioInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lotes.
        /// </summary>
        internal static string Lotes {
            get {
                return ResourceManager.GetString("Lotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento.
        /// </summary>
        internal static string Mantenimiento {
            get {
                return ResourceManager.GetString("Mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa Almacen.
        /// </summary>
        internal static string MapaAlmacen {
            get {
                return ResourceManager.GetString("MapaAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máquinas.
        /// </summary>
        internal static string Maquinas {
            get {
                return ResourceManager.GetString("Maquinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivos Regularización.
        /// </summary>
        internal static string MotivosReg {
            get {
                return ResourceManager.GetString("MotivosReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimientos.
        /// </summary>
        internal static string Movimientos {
            get {
                return ResourceManager.GetString("Movimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operators.
        /// </summary>
        internal static string Operarios {
            get {
                return ResourceManager.GetString("Operarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movimiento Operarios.
        /// </summary>
        internal static string OperariosMov {
            get {
                return ResourceManager.GetString("OperariosMov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Palets Tipo.
        /// </summary>
        internal static string PaletsTipo {
            get {
                return ResourceManager.GetString("PaletsTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parametros.
        /// </summary>
        internal static string Parametros {
            get {
                return ResourceManager.GetString("Parametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        internal static string Permisos {
            get {
                return ResourceManager.GetString("Permisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planificacion.
        /// </summary>
        internal static string Planificacion {
            get {
                return ResourceManager.GetString("Planificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productividad.
        /// </summary>
        internal static string Productividad {
            get {
                return ResourceManager.GetString("Productividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propietarios.
        /// </summary>
        internal static string Propietarios {
            get {
                return ResourceManager.GetString("Propietarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        internal static string Proveedores {
            get {
                return ResourceManager.GetString("Proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores-Pedidos.
        /// </summary>
        internal static string ProveedoresPedidos {
            get {
                return ResourceManager.GetString("ProveedoresPedidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recepciones.
        /// </summary>
        internal static string Recepciones {
            get {
                return ResourceManager.GetString("Recepciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos Tarea.
        /// </summary>
        internal static string RecursosTarea {
            get {
                return ResourceManager.GetString("RecursosTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reposiciones.
        /// </summary>
        internal static string Reposiciones {
            get {
                return ResourceManager.GetString("Reposiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva Histórico.
        /// </summary>
        internal static string ReservaHist {
            get {
                return ResourceManager.GetString("ReservaHist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rutas.
        /// </summary>
        internal static string Rutas {
            get {
                return ResourceManager.GetString("Rutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rutas Preparación.
        /// </summary>
        internal static string RutasPrep {
            get {
                return ResourceManager.GetString("RutasPrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stock Status.
        /// </summary>
        internal static string StockStatus {
            get {
                return ResourceManager.GetString("StockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas Pendientes.
        /// </summary>
        internal static string TareasPendientes {
            get {
                return ResourceManager.GetString("TareasPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TareasTipo.
        /// </summary>
        internal static string TareasTipo {
            get {
                return ResourceManager.GetString("TareasTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trazabilidad.
        /// </summary>
        internal static string Trazabilidad {
            get {
                return ResourceManager.GetString("Trazabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios Grupos.
        /// </summary>
        internal static string UsuariosGrupos {
            get {
                return ResourceManager.GetString("UsuariosGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visor Log.
        /// </summary>
        internal static string VisorLog {
            get {
                return ResourceManager.GetString("VisorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona Intercambio.
        /// </summary>
        internal static string ZonaIntercambio {
            get {
                return ResourceManager.GetString("ZonaIntercambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona Lógica.
        /// </summary>
        internal static string ZonaLogica {
            get {
                return ResourceManager.GetString("ZonaLogica", resourceCulture);
            }
        }
    }
}
