//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RumboSGA.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class telerikStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal telerikStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RumboSGA.Properties.telerikStrings", typeof(telerikStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a acaba en [Valor1].
        /// </summary>
        internal static string AcabaConValue1 {
            get {
                return ResourceManager.GetString("AcabaConValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acaba en.
        /// </summary>
        internal static string AcabaEn {
            get {
                return ResourceManager.GetString("AcabaEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupar por esta columna.
        /// </summary>
        internal static string AgruparPorEstaCoulmna {
            get {
                return ResourceManager.GetString("AgruparPorEstaCoulmna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alineamiento de texto.
        /// </summary>
        internal static string AlineamientoTexto {
            get {
                return ResourceManager.GetString("AlineamientoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alineamiento de texto de fila.
        /// </summary>
        internal static string AlineamientoTextoFila {
            get {
                return ResourceManager.GetString("AlineamientoTextoFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir regla nueva.
        /// </summary>
        internal static string AñadirRegla {
            get {
                return ResourceManager.GetString("AñadirRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        internal static string AndMayusculas {
            get {
                return ResourceManager.GetString("AndMayusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar.
        /// </summary>
        internal static string Aplicar {
            get {
                return ResourceManager.GetString("Aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar este formato a la fila entera.
        /// </summary>
        internal static string AplicarFormatoFilaEntera {
            get {
                return ResourceManager.GetString("AplicarFormatoFilaEntera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar este formato si la fila está seleccionada.
        /// </summary>
        internal static string AplicarFormatoSiFilaSeleccionada {
            get {
                return ResourceManager.GetString("AplicarFormatoSiFilaSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayer.
        /// </summary>
        internal static string Ayer {
            get {
                return ResourceManager.GetString("Ayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar Fila.
        /// </summary>
        internal static string BorrarFila {
            get {
                return ResourceManager.GetString("BorrarFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupar por:.
        /// </summary>
        internal static string CabeceraAgrupaciones {
            get {
                return ResourceManager.GetString("CabeceraAgrupaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos.
        /// </summary>
        internal static string Campos {
            get {
                return ResourceManager.GetString("Campos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click aquí para añadir fila.
        /// </summary>
        internal static string ClickAñadirColumna {
            get {
                return ResourceManager.GetString("ClickAñadirColumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color fondo de celda.
        /// </summary>
        internal static string ColorFondoCelda {
            get {
                return ResourceManager.GetString("ColorFondoCelda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color fondo de fila.
        /// </summary>
        internal static string ColorFondoFila {
            get {
                return ResourceManager.GetString("ColorFondoFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color de texto de celda.
        /// </summary>
        internal static string ColorTextoCelda {
            get {
                return ResourceManager.GetString("ColorTextoCelda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color de texto de fila.
        /// </summary>
        internal static string ColorTextoFila {
            get {
                return ResourceManager.GetString("ColorTextoFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cómo.
        /// </summary>
        internal static string Como {
            get {
                return ResourceManager.GetString("Como", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condición.
        /// </summary>
        internal static string Condicion {
            get {
                return ResourceManager.GetString("Condicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constantes.
        /// </summary>
        internal static string Constantes {
            get {
                return ResourceManager.GetString("Constantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constructor de Expresiones.
        /// </summary>
        internal static string ConstructorExpresiones {
            get {
                return ResourceManager.GetString("ConstructorExpresiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ContenidoEn.
        /// </summary>
        internal static string ContenidoEn {
            get {
                return ResourceManager.GetString("ContenidoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contiene.
        /// </summary>
        internal static string Contiene {
            get {
                return ResourceManager.GetString("Contiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a contiene [Valor1].
        /// </summary>
        internal static string ContieneValue1 {
            get {
                return ResourceManager.GetString("ContieneValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        internal static string Copiar {
            get {
                return ResourceManager.GetString("Copiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cortar.
        /// </summary>
        internal static string Cortar {
            get {
                return ResourceManager.GetString("Cortar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desagrupar esta columna.
        /// </summary>
        internal static string DesagruparEstacolumna {
            get {
                return ResourceManager.GetString("DesagruparEstacolumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Determina si las comparaciones de texto tendrán en cuenta las mayúsculas.
        /// </summary>
        internal static string DescripcionCaseSensitive {
            get {
                return ResourceManager.GetString("DescripcionCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el color de fondo para la celda.
        /// </summary>
        internal static string DescripcionCellBackColor {
            get {
                return ResourceManager.GetString("DescripcionCellBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el color de letra para la celda.
        /// </summary>
        internal static string DescripcionCellForeColor {
            get {
                return ResourceManager.GetString("DescripcionCellForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Determina si la condición está habilitada(puede ser evaluada y aplicada).
        /// </summary>
        internal static string DescripcionEnabled {
            get {
                return ResourceManager.GetString("DescripcionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el color de fondo para la fila entera.
        /// </summary>
        internal static string DescripcionRowBackColor {
            get {
                return ResourceManager.GetString("DescripcionRowBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el color de texto para la fila entera.
        /// </summary>
        internal static string DescripcionRowForeColor {
            get {
                return ResourceManager.GetString("DescripcionRowForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el alineamiento para el texto de las celdas cuando AplicarAFila es verdadero.
        /// </summary>
        internal static string DescripcionRowTextAlignment {
            get {
                return ResourceManager.GetString("DescripcionRowTextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce el alineamiento para el texto de las celdas.
        /// </summary>
        internal static string DescripcionTextAlignment {
            get {
                return ResourceManager.GetString("DescripcionTextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desfijar Columna.
        /// </summary>
        internal static string DesfijarColumna {
            get {
                return ResourceManager.GetString("DesfijarColumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desfijar Fila.
        /// </summary>
        internal static string DesfijarFila {
            get {
                return ResourceManager.GetString("DesfijarFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dividir.
        /// </summary>
        internal static string Dividir {
            get {
                return ResourceManager.GetString("Dividir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor de Expresiones.
        /// </summary>
        internal static string EditorExpresiones {
            get {
                return ResourceManager.GetString("EditorExpresiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empieza con [Valor1].
        /// </summary>
        internal static string EmpiezaConValue1 {
            get {
                return ResourceManager.GetString("EmpiezaConValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empieza con.
        /// </summary>
        internal static string EmpiezaEn {
            get {
                return ResourceManager.GetString("EmpiezaEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EmpiezaCon.
        /// </summary>
        internal static string EmpiezaEn2 {
            get {
                return ResourceManager.GetString("EmpiezaEn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muestra filas donde:.
        /// </summary>
        internal static string EnseñaFilasQue {
            get {
                return ResourceManager.GetString("EnseñaFilasQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entre.
        /// </summary>
        internal static string Entre {
            get {
                return ResourceManager.GetString("Entre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a está entre [Valor1] y  [Valor1].
        /// </summary>
        internal static string EntreValue1Value2 {
            get {
                return ResourceManager.GetString("EntreValue1Value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de Filtro.
        /// </summary>
        internal static string ErrorFiltro {
            get {
                return ResourceManager.GetString("ErrorFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es nulo.
        /// </summary>
        internal static string EsNulo {
            get {
                return ResourceManager.GetString("EsNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduce una expresión válida.
        /// </summary>
        internal static string EstableceExpresionValida {
            get {
                return ResourceManager.GetString("EstableceExpresionValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduce un valor válido para la celda.
        /// </summary>
        internal static string EstableceValoresValidos {
            get {
                return ResourceManager.GetString("EstableceValoresValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor introduce valores válidos para la celda.
        /// </summary>
        internal static string EstableceValorValido {
            get {
                return ResourceManager.GetString("EstableceValorValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Fijado.
        /// </summary>
        internal static string EstadoFijado {
            get {
                return ResourceManager.GetString("EstadoFijado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está Vacio.
        /// </summary>
        internal static string EstaVacio {
            get {
                return ResourceManager.GetString("EstaVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión.
        /// </summary>
        internal static string Expresion {
            get {
                return ResourceManager.GetString("Expresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falso.
        /// </summary>
        internal static string Falso {
            get {
                return ResourceManager.GetString("Falso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fijar abajo.
        /// </summary>
        internal static string FijarAbajo {
            get {
                return ResourceManager.GetString("FijarAbajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fijar arriba.
        /// </summary>
        internal static string FijarArriba {
            get {
                return ResourceManager.GetString("FijarArriba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fijar a la derecha.
        /// </summary>
        internal static string FijarDerecha {
            get {
                return ResourceManager.GetString("FijarDerecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fijar a la izquierda.
        /// </summary>
        internal static string FijarIzquierda {
            get {
                return ResourceManager.GetString("FijarIzquierda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BuscarDesdePosicionActual.
        /// </summary>
        internal static string FilaBusquedaBuscarDesdePosActual {
            get {
                return ResourceManager.GetString("FilaBusquedaBuscarDesdePosActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CasoEncontrado.
        /// </summary>
        internal static string FilaBusquedaCasoEncontrado {
            get {
                return ResourceManager.GetString("FilaBusquedaCasoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FilaBusquedaElegirColumnas.
        /// </summary>
        internal static string FilaBusquedaElegircolumna {
            get {
                return ResourceManager.GetString("FilaBusquedaElegircolumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SearchRowMenuItemChildTemplates.
        /// </summary>
        internal static string FilaBusquedaPlantillaHija {
            get {
                return ResourceManager.GetString("FilaBusquedaPlantillaHija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SearchRowMenuItemMasterTemplate.
        /// </summary>
        internal static string FilaBusquedaPlantillaMaestra {
            get {
                return ResourceManager.GetString("FilaBusquedaPlantillaMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SearchRowResultsOfLabel.
        /// </summary>
        internal static string FilaBusquedaResultadosEtiqueta {
            get {
                return ResourceManager.GetString("FilaBusquedaResultadosEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SearchRowTextBoxNullText.
        /// </summary>
        internal static string FilaBusquedaTextBoxTextoNulo {
            get {
                return ResourceManager.GetString("FilaBusquedaTextBoxTextoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SearchRowMenuItemAllColumns.
        /// </summary>
        internal static string FilaBusquedaTodasColumnas {
            get {
                return ResourceManager.GetString("FilaBusquedaTodasColumnas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por fecha especifica:.
        /// </summary>
        internal static string FiltrarPorFechas {
            get {
                return ResourceManager.GetString("FiltrarPorFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El filtro compuesto no es válido.
        /// </summary>
        internal static string FiltroCompuestoNoValido {
            get {
                return ResourceManager.GetString("FiltroCompuestoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros Disponibles.
        /// </summary>
        internal static string FiltrosDisponibles {
            get {
                return ResourceManager.GetString("FiltrosDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar formato a celdas con.
        /// </summary>
        internal static string FormatearSoloCeldas {
            get {
                return ResourceManager.GetString("FormatearSoloCeldas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato.
        /// </summary>
        internal static string Formato {
            get {
                return ResourceManager.GetString("Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato Condicional.
        /// </summary>
        internal static string FormatoCondicional {
            get {
                return ResourceManager.GetString("FormatoCondicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funciones.
        /// </summary>
        internal static string Funciones {
            get {
                return ResourceManager.GetString("Funciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enabled.
        /// </summary>
        internal static string Habilitado {
            get {
                return ResourceManager.GetString("Habilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoy.
        /// </summary>
        internal static string Hoy {
            get {
                return ResourceManager.GetString("Hoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Igual.
        /// </summary>
        internal static string Igual {
            get {
                return ResourceManager.GetString("Igual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a igual que [Valor1].
        /// </summary>
        internal static string IgualValue1 {
            get {
                return ResourceManager.GetString("IgualValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Filtro.
        /// </summary>
        internal static string LimpiarFiltro {
            get {
                return ResourceManager.GetString("LimpiarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Ordenación.
        /// </summary>
        internal static string LimpiarOrdenacion {
            get {
                return ResourceManager.GetString("LimpiarOrdenacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Valor.
        /// </summary>
        internal static string LimpiarValor {
            get {
                return ResourceManager.GetString("LimpiarValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logical.
        /// </summary>
        internal static string Logical {
            get {
                return ResourceManager.GetString("Logical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logical \&quot;AND\&quot;&quot;.
        /// </summary>
        internal static string LogicalAND {
            get {
                return ResourceManager.GetString("LogicalAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logical \&quot;NOT\&quot;&quot;.
        /// </summary>
        internal static string LogicalNOT {
            get {
                return ResourceManager.GetString("LogicalNOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logical \&quot;OR\&quot;&quot;.
        /// </summary>
        internal static string LogicalOR {
            get {
                return ResourceManager.GetString("LogicalOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestor de Reglas de Formato Condicional.
        /// </summary>
        internal static string ManagerReglasFormateo {
            get {
                return ResourceManager.GetString("ManagerReglasFormateo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más.
        /// </summary>
        internal static string Mas {
            get {
                return ResourceManager.GetString("Mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Math.
        /// </summary>
        internal static string Math {
            get {
                return ResourceManager.GetString("Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor.
        /// </summary>
        internal static string Mayor {
            get {
                return ResourceManager.GetString("Mayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor o Igual que.
        /// </summary>
        internal static string MayorIgual {
            get {
                return ResourceManager.GetString("MayorIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es mayor o igual que [Valor1].
        /// </summary>
        internal static string MayorIgualValue1 {
            get {
                return ResourceManager.GetString("MayorIgualValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor o Igual.
        /// </summary>
        internal static string MayorOIgual {
            get {
                return ResourceManager.GetString("MayorOIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor que.
        /// </summary>
        internal static string MayorQue {
            get {
                return ResourceManager.GetString("MayorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es mayor que [Valor1].
        /// </summary>
        internal static string MayorQueValue1 {
            get {
                return ResourceManager.GetString("MayorQueValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor Ajuste.
        /// </summary>
        internal static string MejorAjuste {
            get {
                return ResourceManager.GetString("MejorAjuste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor.
        /// </summary>
        internal static string Menor {
            get {
                return ResourceManager.GetString("Menor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor o igual que.
        /// </summary>
        internal static string MenorIgual {
            get {
                return ResourceManager.GetString("MenorIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es menor o igual que [Valor1].
        /// </summary>
        internal static string MenorIgualValue1 {
            get {
                return ResourceManager.GetString("MenorIgualValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor o Igual.
        /// </summary>
        internal static string MenorOIgual {
            get {
                return ResourceManager.GetString("MenorOIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor que.
        /// </summary>
        internal static string MenorQue {
            get {
                return ResourceManager.GetString("MenorQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es menor que [Valor1].
        /// </summary>
        internal static string MenorQueValue1 {
            get {
                return ResourceManager.GetString("MenorQueValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menos.
        /// </summary>
        internal static string Menos {
            get {
                return ResourceManager.GetString("Menos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastra la cabecera de una columna aquí\npara quitarla de la vista actual.
        /// </summary>
        internal static string MensajeColumnChooser {
            get {
                return ResourceManager.GetString("MensajeColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastra una columna para agrupar por ella.
        /// </summary>
        internal static string MensajePanelAgrupacion {
            get {
                return ResourceManager.GetString("MensajePanelAgrupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Descriptor de Fuente.
        /// </summary>
        internal static string MiDescriptorFuente {
            get {
                return ResourceManager.GetString("MiDescriptorFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Fuente de Celda.
        /// </summary>
        internal static string MiFuenteCelda {
            get {
                return ResourceManager.GetString("MiFuenteCelda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modulo.
        /// </summary>
        internal static string Modulo {
            get {
                return ResourceManager.GetString("Modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiplicar.
        /// </summary>
        internal static string Multiplicar {
            get {
                return ResourceManager.GetString("Multiplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NoComo.
        /// </summary>
        internal static string NoComo {
            get {
                return ResourceManager.GetString("NoComo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NoContenidoEn.
        /// </summary>
        internal static string NoContenidoEn {
            get {
                return ResourceManager.GetString("NoContenidoEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No contiene.
        /// </summary>
        internal static string NoContiene {
            get {
                return ResourceManager.GetString("NoContiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NoContiene.
        /// </summary>
        internal static string NoContiene2 {
            get {
                return ResourceManager.GetString("NoContiene2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no contiene [Valor1].
        /// </summary>
        internal static string NoContieneValue1 {
            get {
                return ResourceManager.GetString("NoContieneValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No entre.
        /// </summary>
        internal static string NoEntre {
            get {
                return ResourceManager.GetString("NoEntre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no está entre [Valor1] y [Valor1].
        /// </summary>
        internal static string NoEntreValue1Value2 {
            get {
                return ResourceManager.GetString("NoEntreValue1Value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No igual a.
        /// </summary>
        internal static string NoIgual {
            get {
                return ResourceManager.GetString("NoIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NoIgual.
        /// </summary>
        internal static string NoIgual2 {
            get {
                return ResourceManager.GetString("NoIgual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is not equal to [Value1].
        /// </summary>
        internal static string NoIgualValue1 {
            get {
                return ResourceManager.GetString("NoIgualValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Regla.
        /// </summary>
        internal static string NombreRegla {
            get {
                return ResourceManager.GetString("NombreRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es nulo.
        /// </summary>
        internal static string NoNulo {
            get {
                return ResourceManager.GetString("NoNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NoNulo.
        /// </summary>
        internal static string NoNulo2 {
            get {
                return ResourceManager.GetString("NoNulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Nulo.
        /// </summary>
        internal static string NoNulo3 {
            get {
                return ResourceManager.GetString("NoNulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO.
        /// </summary>
        internal static string NotMayusculas {
            get {
                return ResourceManager.GetString("NotMayusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está vacio.
        /// </summary>
        internal static string NoVacio {
            get {
                return ResourceManager.GetString("NoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NoVacio.
        /// </summary>
        internal static string NoVacio2 {
            get {
                return ResourceManager.GetString("NoVacio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nulo.
        /// </summary>
        internal static string Nulo {
            get {
                return ResourceManager.GetString("Nulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar Columna.
        /// </summary>
        internal static string OcultarColumna {
            get {
                return ResourceManager.GetString("OcultarColumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar Grupo.
        /// </summary>
        internal static string OcultarGrupo {
            get {
                return ResourceManager.GetString("OcultarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operadores.
        /// </summary>
        internal static string Operadores {
            get {
                return ResourceManager.GetString("Operadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar Ascendente.
        /// </summary>
        internal static string OrdenarAscendente {
            get {
                return ResourceManager.GetString("OrdenarAscendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar columnas alfabéticamente.
        /// </summary>
        internal static string OrdenarColumnasAlfabeticamente {
            get {
                return ResourceManager.GetString("OrdenarColumnasAlfabeticamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar Descendente.
        /// </summary>
        internal static string OrdenarDescendente {
            get {
                return ResourceManager.GetString("OrdenarDescendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OR.
        /// </summary>
        internal static string OrMayusculas {
            get {
                return ResourceManager.GetString("OrMayusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        internal static string Otro {
            get {
                return ResourceManager.GetString("Otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagina.
        /// </summary>
        internal static string PanelPaginacionEtiqueta {
            get {
                return ResourceManager.GetString("PanelPaginacionEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de.
        /// </summary>
        internal static string PanelPaginacionOfPagesEtiqueta {
            get {
                return ResourceManager.GetString("PanelPaginacionOfPagesEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CambiarAtributos invalidos.
        /// </summary>
        internal static string ParametrosInvalidos {
            get {
                return ResourceManager.GetString("ParametrosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pegar.
        /// </summary>
        internal static string Pegar {
            get {
                return ResourceManager.GetString("Pegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        internal static string Personalizado {
            get {
                return ResourceManager.GetString("Personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previsualizar resultado.
        /// </summary>
        internal static string PrevisualizarResultado {
            get {
                return ResourceManager.GetString("PrevisualizarResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades de Regla.
        /// </summary>
        internal static string PropiedadesRegla {
            get {
                return ResourceManager.GetString("PropiedadesRegla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar.
        /// </summary>
        internal static string Quitar {
            get {
                return ResourceManager.GetString("Quitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regla aplica a.
        /// </summary>
        internal static string ReglaAplicaA {
            get {
                return ResourceManager.GetString("ReglaAplicaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reglas.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Selecciona Uno].
        /// </summary>
        internal static string SeleccionaUno {
            get {
                return ResourceManager.GetString("SeleccionaUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selector de Columnas.
        /// </summary>
        internal static string SelectorColumnas {
            get {
                return ResourceManager.GetString("SelectorColumnas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor selecciona un valor de celda válido.
        /// </summary>
        internal static string SelecValorValido {
            get {
                return ResourceManager.GetString("SelecValorValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SensibleMayusculas.
        /// </summary>
        internal static string SensibleMayusculas {
            get {
                return ResourceManager.GetString("SensibleMayusculas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin datos que mostrar.
        /// </summary>
        internal static string SinDatosQueMostrar {
            get {
                return ResourceManager.GetString("SinDatosQueMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin filtro.
        /// </summary>
        internal static string SinFiltro {
            get {
                return ResourceManager.GetString("SinFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        internal static string Texto {
            get {
                return ResourceManager.GetString("Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        internal static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los resultados de busqueda.
        /// </summary>
        internal static string TodosResultadosBusqueda {
            get {
                return ResourceManager.GetString("TodosResultadosBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En los últimos 7 días.
        /// </summary>
        internal static string Ultimos7Dias {
            get {
                return ResourceManager.GetString("Ultimos7Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vacio.
        /// </summary>
        internal static string Vacio {
            get {
                return ResourceManager.GetString("Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor 1.
        /// </summary>
        internal static string Valor1 {
            get {
                return ResourceManager.GetString("Valor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor 2.
        /// </summary>
        internal static string Valor2 {
            get {
                return ResourceManager.GetString("Valor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor de celda.
        /// </summary>
        internal static string ValorCelda {
            get {
                return ResourceManager.GetString("ValorCelda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verdadero.
        /// </summary>
        internal static string Verdadero {
            get {
                return ResourceManager.GetString("Verdadero", resourceCulture);
            }
        }
    }
}
